global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    project: "telegrambot-mytech"

scrape_configs:
  - job_name: "prediction-api"
    static_configs:
      - targets: ["prediction-api:8001"]
    metrics_path: /metrics

  - job_name: "data-api"
    static_configs:
      - targets: ["data-api:8002"]
    metrics_path: /metrics

  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]
